const heroes = [
  { name: "Miya", roles: ["Marksman", "Tank"], lanes: ["Gold"], icon: "icons/Miya.png" },
  { name: "Balmond", roles: ["Fighter", "Mage"], lanes: ["Jungle"], icon: "icons/Balmond.png" },
  { name: "Saber", roles: ["Assassin", "Fighter"], lanes: ["Jungle", "Roam"], icon: "icons/Saber.png" },
  { name: "Alice", roles: ["Tank", "Mage"], lanes: ["Exp"], icon: "icons/Alice.png" },
  { name: "Nana", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Nana.png" },
  { name: "Tigreal", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Tigreal.png" },
  { name: "Alucard", roles: ["Fighter", "Assassin"], lanes: ["Exp"], icon: "icons/Alucard.png" },
  { name: "Karina", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Karina.png" },
  { name: "Akai", roles: ["Tank"], lanes: ["Exp", "Jungle", "Roam"], icon: "icons/Akai.png" },
  { name: "Franco", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Franco.png" },
  { name: "Bane", roles: ["Fighter", "Mage"], lanes: ["Jungle", "Gold"], icon: "icons/Bane.png" },
  { name: "Bruno", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Bruno.png" },
  { name: "Clint", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Clint.png" },
  { name: "Rafaela", roles: ["Support"], lanes: ["Roam"], icon: "icons/Rafaela.png" },
  { name: "Eudora", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Eudora.png" },
  { name: "Zilong", roles: ["Fighter", "Assassin"], lanes: ["Jungle", "Gold"], icon: "icons/Zilong.png" },
  { name: "Fanny", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Fanny.png" },
  { name: "Layla", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Layla.png" },
  { name: "Minotaur", roles: ["Tank", "Support"], lanes: ["Roam"], icon: "icons/Minotaur.png" },
  { name: "Lolita", roles: ["Support", "Tank"], lanes: ["Roam"], icon: "icons/Lolita.png" },
  { name: "Hayabusa", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Hayabusa.png" },
  { name: "Freya", roles: ["Fighter"], lanes: ["Jungle", "Gold"], icon: "icons/Freya.png" },
  { name: "Gord", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Gord.png" },
  { name: "Natalia", roles: ["Assassin"], lanes: ["Roam", "Gold"], icon: "icons/Natalia.png" },
  { name: "Kagura", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Kagura.png" },
  { name: "Chou", roles: ["Fighter"], lanes: ["Roam"], icon: "icons/Chou.png" },
  { name: "Sun", roles: ["Fighter"], lanes: ["Jungle", "Gold"], icon: "icons/Sun.png" },
  { name: "Alpha", roles: ["Fighter"], lanes: ["Jungle"], icon: "icons/Alpha.png" },
  { name: "Ruby", roles: ["Fighter"], lanes: ["Exp", "Roam", "Gold"], icon: "icons/Ruby.png" },
  { name: "Yi Sun-shin", roles: ["Assassin", "Marksman"], lanes: ["Jungle"], icon: "icons/Yi Sun-shin.png" },
  { name: "Moskov", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Moskov.png" },
  { name: "Johnson", roles: ["Tank", "Support"], lanes: ["Roam"], icon: "icons/Johnson.png" },
  { name: "Cyclops", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Cyclops.png" },
  { name: "Estes", roles: ["Support"], lanes: ["Roam"], icon: "icons/Estes.png" },
  { name: "Hilda", roles: ["Fighter", "Tank"], lanes: ["Exp", "Roam"], icon: "icons/Hilda.png" },
  { name: "Aurora", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Aurora.png" },
  { name: "Lapu-Lapu", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Lapu-Lapu.png" },
  { name: "Vexana", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Vexana.png" },
  { name: "Roger", roles: ["Fighter", "Marksman"], lanes: ["Jungle", "Gold"], icon: "icons/Roger.png" },
  { name: "Karrie", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Karrie.png" },
  { name: "Gatotkaca", roles: ["Tank", "Fighter"], lanes: ["Exp", "Roam"], icon: "icons/Gatotkaca.png" },
  { name: "Harley", roles: ["Assassin", "Mage"], lanes: ["Jungle"], icon: "icons/Harley.png" },
  { name: "Irithel", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Irithel.png" },
  { name: "Grock", roles: ["Tank", "Fighter"], lanes: ["Roam"], icon: "icons/Grock.png" },
  { name: "Argus", roles: ["Fighter"], lanes: ["Exp", "Gold"], icon: "icons/Argus.png" },
  { name: "Odette", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Odette.png" },
  { name: "Lancelot", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Lancelot.png" },
  { name: "Diggie", roles: ["Support"], lanes: ["Roam"], icon: "icons/Diggie.png" },
  { name: "Hylos", roles: ["Tank"], lanes: ["Exp", "Roam"], icon: "icons/Hylos.png" },
  { name: "Zhask", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Zhask.png" },
  { name: "Helcurt", roles: ["Assassin"], lanes: ["Exp", "Roam", "Gold"], icon: "icons/Helcurt.png" },
  { name: "Pharsa", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Pharsa.png" },
  { name: "Lesley", roles: ["Marksman", "Assassin"], lanes: ["Gold"], icon: "icons/Lesley.png" },
  { name: "Jawhead", roles: ["Fighter"], lanes: ["Roam"], icon: "icons/Jawhead.png" },
  { name: "Angela", roles: ["Support"], lanes: ["Mid", "Roam"], icon: "icons/Angela.png" },
  { name: "Gusion", roles: ["Assassin"], lanes: ["Jungle", "Mid"], icon: "icons/Gusion.png" },
  { name: "Valir", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Valir.png" },
  { name: "Martis", roles: ["Fighter"], lanes: ["Jungle"], icon: "icons/Martis.png" },
  { name: "Uranus", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Uranus.png" },
  { name: "Hanabi", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Hanabi.png" },
  { name: "Chang'e", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Chang'e.png" },
  { name: "Kaja", roles: ["Support", "Fighter"], lanes: ["Jungle", "Roam"], icon: "icons/Kaja.png" },
  { name: "Selena", roles: ["Assassin", "Mage"], lanes: ["Mid"], icon: "icons/Selena.png" },
  { name: "Aldous", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Aldous.png" },
  { name: "Claude", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Claude.png" },
  { name: "Vale", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Vale.png" },
  { name: "Leomord", roles: ["Fighter"], lanes: ["Jungle"], icon: "icons/Leomord.png" },
  { name: "Lunox", roles: ["Mage"], lanes: ["Mid", "Gold"], icon: "icons/Lunox.png" },
  { name: "Hanzo", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Hanzo.png" },
  { name: "Belerick", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Belerick.png" },
  { name: "Kimmy", roles: ["Marksman", "Mage"], lanes: ["Mid", "Gold"], icon: "icons/Kimmy.png" },
  { name: "Thamuz", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Thamuz.png" },
  { name: "Harith", roles: ["Mage"], lanes: ["Gold"], icon: "icons/Harith.png" },
  { name: "Minsitthar", roles: ["Fighter"], lanes: ["Gold"], icon: "icons/Minsitthar.png" },
  { name: "Kadita", roles: ["Mage", "Assassin"], lanes: ["Mid"], icon: "icons/Kadita.png" },
  { name: "Faramis", roles: ["Support", "Mage"], lanes: ["Mid"], icon: "icons/Faramis.png" },
  { name: "Badang", roles: ["Fighter"], lanes: ["Exp", "Roam"], icon: "icons/Badang.png" },
  { name: "Khufra", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Khufra.png" },
  { name: "Granger", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Granger.png" },
  { name: "Guinevere", roles: ["Fighter"], lanes: ["Jungle", "Roam"], icon: "icons/Guinevere.png" },
  { name: "Esmeralda", roles: ["Tank", "Mage"], lanes: ["Exp", "Gold"], icon: "icons/Esmeralda.png" },
  { name: "Terizla", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Terizla.png" },
  { name: "X Borg", roles: ["Fighter"], lanes: ["Exp", "Jungle", "Gold"], icon: "icons/X Borg.png" },
  { name: "Ling", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Ling.png" },
  { name: "Dyrroth", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Dyrroth.png" },
  { name: "Lylia", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Lylia.png" },
  { name: "Baxia", roles: ["Tank"], lanes: ["Jungle", "Roam"], icon: "icons/Baxia.png" },
  { name: "Masha", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Masha.png" },
  { name: "Wanwan", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Wanwan.png" },
  { name: "Silvanna", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Silvanna.png" },
  { name: "Cecilion", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Cecilion.png" },
  { name: "Carmilla", roles: ["Support", "Tank"], lanes: ["Roam"], icon: "icons/Carmilla.png" },
  { name: "Atlas", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Atlas.png" },
  { name: "Popol and Kupa", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Popol and Kupa.png" },
  { name: "Yu Zhong", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Yu Zhong.png" },
  { name: "Luo Yi", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Luo Yi.png" },
  { name: "Benedetta", roles: ["Assassin"], lanes: ["Exp", "Jungle"], icon: "icons/Benedetta.png" },
  { name: "Khaleed", roles: ["Fighter"], lanes: ["Exp", "Roam"], icon: "icons/Khaleed.png" },
  { name: "Barats", roles: ["Fighter", "Tank"], lanes: ["Exp", "Jungle"], icon: "icons/Barats.png" },
  { name: "Brody", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Brody.png" },
  { name: "Yve", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Yve.png" },
  { name: "Mathilda", roles: ["Support", "Assassin"], lanes: ["Roam"], icon: "icons/Mathilda.png" },
  { name: "Paquito", roles: ["Fighter"], lanes: ["Exp", "Jungle", "Gold"], icon: "icons/Paquito.png" },
  { name: "Gloo", roles: ["Tank"], lanes: ["Exp"], icon: "icons/Gloo.png" },
  { name: "Beatrix", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Beatrix.png" },
  { name: "Phoveus", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Phoveus.png" },
  { name: "Natan", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Natan.png" },
  { name: "Aulus", roles: ["Fighter"], lanes: ["Jungle", "Gold"], icon: "icons/Aulus.png" },
  { name: "Aamon", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Aamon.png" },
  { name: "Valentina", roles: ["Mage"], lanes: ["Exp", "Mid", "Gold"], icon: "icons/Valentina.png" },
  { name: "Edith", roles: ["Tank"], lanes: ["Exp", "Roam"], icon: "icons/Edith.png" },
  { name: "Floryn", roles: ["Support"], lanes: ["Roam"], icon: "icons/Floryn.png" },
  { name: "Yin", roles: ["Fighter", "Assassin"], lanes: ["Jungle"], icon: "icons/Yin.png" },
  { name: "Melissa", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Melissa.png" },
  { name: "Xavier", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Xavier.png" },
  { name: "Julian", roles: ["Assassin", "Fighter"], lanes: ["Jungle"], icon: "icons/Julian.png" },
  { name: "Fredrinn", roles: ["Fighter", "Tank"], lanes: ["Jungle"], icon: "icons/Fredrinn.png" },
  { name: "Joy", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Joy.png" },
  { name: "Novaria", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Novaria.png" },
  { name: "Arlott", roles: ["Fighter", "Assassin"], lanes: ["Exp"], icon: "icons/Arlott.png" },
  { name: "Ixia", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Ixia.png" },
  { name: "Nolan", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Nolan.png" },
  { name: "Cici", roles: ["Fighter"], lanes: ["Exp", "Gold"], icon: "icons/Cici.png" },
  { name: "Chip", roles: ["Support", "Tank"], lanes: ["Roam"], icon: "icons/Chip.png" },
  { name: "Zhuxin", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Zhuxin.png" },
  { name: "Suyou", roles: ["Assassin", "Fighter"], lanes: ["Jungle"], icon: "icons/Suyou.png" },
  { name: "Lukas", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Lukas.png" },
  { name: "Kalea", roles: ["Support"], lanes: ["Roam"], icon: "icons/Kalea.png" },
  { name: "Zetian", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Zetian.png" },
  { name: "Obsidia", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Obsidia.png" },
  { name: "Sora", roles: ["Fighter", "Assassin"], lanes: ["Exp", "Gold"], icon: "icons/Sora.png" }

];
