const heroes = [
  { name: "Miya", roles: ["Marksman", "Tank"], lanes: ["Gold"], icon: "icons/Miya.png", metaTier: "B" },
  { name: "Balmond", roles: ["Fighter", "Mage"], lanes: ["Jungle"], icon: "icons/Balmond.png", metaTier: "F" },
  { name: "Saber", roles: ["Assassin", "Fighter"], lanes: ["Jungle", "Roam"], icon: "icons/Saber.png", metaTier: "F" },
  { name: "Alice", roles: ["Tank", "Mage"], lanes: ["Exp"], icon: "icons/Alice.png", metaTier: "A" },
  { name: "Nana", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Nana.png", metaTier: "F" },
  { name: "Tigreal", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Tigreal.png", metaTier: "B" },
  { name: "Alucard", roles: ["Fighter", "Assassin"], lanes: ["Exp", "Jungle"], icon: "icons/Alucard.png", metaTier: "F" },
  { name: "Karina", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Karina.png", metaTier: "F" },
  { name: "Akai", roles: ["Tank"], lanes: ["Exp", "Jungle", "Roam"], icon: "icons/Akai.png", metaTier: "Situational" },
  { name: "Franco", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Franco.png", metaTier: "Situational" },
  { name: "Bane", roles: ["Fighter", "Mage"], lanes: ["Jungle", "Gold"], icon: "icons/Bane.png", metaTier: "F" },
  { name: "Bruno", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Bruno.png", metaTier: "F" },
  { name: "Clint", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Clint.png", metaTier: "F" },
  { name: "Rafaela", roles: ["Support"], lanes: ["Roam"], icon: "icons/Rafaela.png", metaTier: "Situational" },
  { name: "Eudora", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Eudora.png", metaTier: "B" },
  { name: "Zilong", roles: ["Fighter", "Assassin"], lanes: ["Jungle", "Gold"], icon: "icons/Zilong.png", metaTier: "F" },
  { name: "Fanny", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Fanny.png", metaTier: "S" },
  { name: "Layla", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Layla.png", metaTier: "F" },
  { name: "Minotaur", roles: ["Tank", "Support"], lanes: ["Roam"], icon: "icons/Minotaur.png", metaTier: "B" },
  { name: "Lolita", roles: ["Support", "Tank"], lanes: ["Roam"], icon: "icons/Lolita.png", metaTier: "F" },
  { name: "Hayabusa", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Hayabusa.png", metaTier: "A" },
  { name: "Freya", roles: ["Fighter"], lanes: ["Jungle", "Gold"], icon: "icons/Freya.png", metaTier: "S" },
  { name: "Gord", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Gord.png", metaTier: "F" },
  { name: "Natalia", roles: ["Assassin"], lanes: ["Roam", "Gold"], icon: "icons/Natalia.png", metaTier: "F" },
  { name: "Kagura", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Kagura.png", metaTier: "B" },
  { name: "Chou", roles: ["Fighter"], lanes: ["Roam"], icon: "icons/Chou.png", metaTier: "S" },
  { name: "Sun", roles: ["Fighter"], lanes: ["Jungle", "Gold"], icon: "icons/Sun.png", metaTier: "F" },
  { name: "Alpha", roles: ["Fighter"], lanes: ["Jungle"], icon: "icons/Alpha.png", metaTier: "Situational" },
  { name: "Ruby", roles: ["Fighter"], lanes: ["Exp", "Roam", "Gold"], icon: "icons/Ruby.png", metaTier: "B" },
  { name: "Yi Sun-shin", roles: ["Assassin", "Marksman"], lanes: ["Jungle"], icon: "icons/Yi Sun-shin.png", metaTier: "S" },
  { name: "Moskov", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Moskov.png", metaTier: "A" },
  { name: "Johnson", roles: ["Tank", "Support"], lanes: ["Roam"], icon: "icons/Johnson.png", metaTier: "F" },
  { name: "Cyclops", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Cyclops.png", metaTier: "F" },
  { name: "Estes", roles: ["Support"], lanes: ["Roam"], icon: "icons/Estes.png", metaTier: "Situational" },
  { name: "Hilda", roles: ["Fighter", "Tank"], lanes: ["Exp", "Roam"], icon: "icons/Hilda.png", metaTier: "S" },
  { name: "Aurora", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Aurora.png", metaTier: "Situational" },
  { name: "Lapu-Lapu", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Lapu-Lapu.png", metaTier: "S" },
  { name: "Vexana", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Vexana.png", metaTier: "F" },
  { name: "Roger", roles: ["Fighter", "Marksman"], lanes: ["Jungle", "Gold"], icon: "icons/Roger.png", metaTier: "F" },
  { name: "Karrie", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Karrie.png", metaTier: "A" },
  { name: "Gatotkaca", roles: ["Tank", "Fighter"], lanes: ["Exp", "Roam"], icon: "icons/Gatotkaca.png", metaTier: "S" },
  { name: "Harley", roles: ["Assassin", "Mage"], lanes: ["Jungle"], icon: "icons/Harley.png", metaTier: "Situational" },
  { name: "Irithel", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Irithel.png", metaTier: "F" },
  { name: "Grock", roles: ["Tank", "Fighter"], lanes: ["Roam"], icon: "icons/Grock.png", metaTier: "S" },
  { name: "Argus", roles: ["Fighter"], lanes: ["Exp", "Gold"], icon: "icons/Argus.png", metaTier: "F" },
  { name: "Odette", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Odette.png", metaTier: "F" },
  { name: "Lancelot", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Lancelot.png", metaTier: "A" },
  { name: "Diggie", roles: ["Support"], lanes: ["Roam"], icon: "icons/Diggie.png", metaTier: "Situational" },
  { name: "Hylos", roles: ["Tank"], lanes: ["Exp", "Roam"], icon: "icons/Hylos.png", metaTier: "A" },
  { name: "Zhask", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Zhask.png", metaTier: "F" },
  { name: "Helcurt", roles: ["Assassin"], lanes: ["Exp", "Roam", "Gold"], icon: "icons/Helcurt.png", metaTier: "Situational" },
  { name: "Pharsa", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Pharsa.png", metaTier: "S" },
  { name: "Lesley", roles: ["Marksman", "Assassin"], lanes: ["Gold"], icon: "icons/Lesley.png", metaTier: "F" },
  { name: "Jawhead", roles: ["Fighter"], lanes: ["Roam"], icon: "icons/Jawhead.png", metaTier: "F" },
  { name: "Angela", roles: ["Support"], lanes: ["Mid", "Roam"], icon: "icons/Angela.png", metaTier: "Situational" },
  { name: "Gusion", roles: ["Assassin"], lanes: ["Jungle", "Mid"], icon: "icons/Gusion.png", metaTier: "F" },
  { name: "Valir", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Valir.png", metaTier: "F" },
  { name: "Martis", roles: ["Fighter"], lanes: ["Jungle"], icon: "icons/Martis.png", metaTier: "Situational" },
  { name: "Uranus", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Uranus.png", metaTier: "S" },
  { name: "Hanabi", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Hanabi.png", metaTier: "F" },
  { name: "Chang'e", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Chang'e.png", metaTier: "F" },
  { name: "Kaja", roles: ["Support", "Fighter"], lanes: ["Jungle", "Roam"], icon: "icons/Kaja.png", metaTier: "Situational" },
  { name: "Selena", roles: ["Assassin", "Mage"], lanes: ["Mid"], icon: "icons/Selena.png", metaTier: "Situational" },
  { name: "Aldous", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Aldous.png", metaTier: "F" },
  { name: "Claude", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Claude.png", metaTier: "S" },
  { name: "Vale", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Vale.png", metaTier: "F" },
  { name: "Leomord", roles: ["Fighter"], lanes: ["Jungle"], icon: "icons/Leomord.png", metaTier: "A" },
  { name: "Lunox", roles: ["Mage"], lanes: ["Mid", "Gold"], icon: "icons/Lunox.png", metaTier: "A" },
  { name: "Hanzo", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Hanzo.png", metaTier: "B" },
  { name: "Belerick", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Belerick.png", metaTier: "F" },
  { name: "Kimmy", roles: ["Marksman", "Mage"], lanes: ["Mid", "Gold"], icon: "icons/Kimmy.png", metaTier: "A" },
  { name: "Thamuz", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Thamuz.png", metaTier: "Situational" },
  { name: "Harith", roles: ["Mage"], lanes: ["Gold"], icon: "icons/Harith.png", metaTier: "A" },
  { name: "Minsitthar", roles: ["Fighter"], lanes: ["Gold"], icon: "icons/Minsitthar.png", metaTier: "F" },
  { name: "Kadita", roles: ["Mage", "Assassin"], lanes: ["Mid"], icon: "icons/Kadita.png", metaTier: "B" },
  { name: "Faramis", roles: ["Support", "Mage"], lanes: ["Mid"], icon: "icons/Faramis.png", metaTier: "F" },
  { name: "Badang", roles: ["Fighter"], lanes: ["Exp", "Roam"], icon: "icons/Badang.png", metaTier: "B" },
  { name: "Khufra", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Khufra.png", metaTier: "F" },
  { name: "Granger", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Granger.png", metaTier: "S" },
  { name: "Guinevere", roles: ["Fighter"], lanes: ["Jungle", "Roam"], icon: "icons/Guinevere.png", metaTier: "B" },
  { name: "Esmeralda", roles: ["Tank", "Mage"], lanes: ["Exp", "Gold"], icon: "icons/Esmeralda.png", metaTier: "S" },
  { name: "Terizla", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Terizla.png", metaTier: "B" },
  { name: "X Borg", roles: ["Fighter"], lanes: ["Exp", "Jungle", "Gold"], icon: "icons/X Borg.png", metaTier: "B" },
  { name: "Ling", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Ling.png", metaTier: "Situational" },
  { name: "Dyrroth", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Dyrroth.png", metaTier: "F" },
  { name: "Lylia", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Lylia.png", metaTier: "B" },
  { name: "Baxia", roles: ["Tank"], lanes: ["Jungle", "Roam"], icon: "icons/Baxia.png", metaTier: "B" },
  { name: "Masha", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Masha.png", metaTier: "F" },
  { name: "Wanwan", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Wanwan.png", metaTier: "F" },
  { name: "Silvanna", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Silvanna.png", metaTier: "F" },
  { name: "Cecilion", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Cecilion.png", metaTier: "Situational" },
  { name: "Carmilla", roles: ["Support", "Tank"], lanes: ["Roam"], icon: "icons/Carmilla.png", metaTier: "F" },
  { name: "Atlas", roles: ["Tank"], lanes: ["Roam"], icon: "icons/Atlas.png", metaTier: "F" },
  { name: "Popol and Kupa", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Popol and Kupa.png", metaTier: "F" },
  { name: "Yu Zhong", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Yu Zhong.png", metaTier: "S" },
  { name: "Luo Yi", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Luo Yi.png", metaTier: "Situational" },
  { name: "Benedetta", roles: ["Assassin"], lanes: ["Exp", "Jungle"], icon: "icons/Benedetta.png", metaTier: "Situational" },
  { name: "Khaleed", roles: ["Fighter"], lanes: ["Exp", "Roam"], icon: "icons/Khaleed.png", metaTier: "A" },
  { name: "Barats", roles: ["Fighter", "Tank"], lanes: ["Exp", "Jungle"], icon: "icons/Barats.png", metaTier: "F" },
  { name: "Brody", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Brody.png", metaTier: "F" },
  { name: "Yve", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Yve.png", metaTier: "S" },
  { name: "Mathilda", roles: ["Support", "Assassin"], lanes: ["Roam"], icon: "icons/Mathilda.png", metaTier: "Situational" },
  { name: "Paquito", roles: ["Fighter"], lanes: ["Exp", "Jungle", "Gold"], icon: "icons/Paquito.png", metaTier: "Situational" },
  { name: "Gloo", roles: ["Tank"], lanes: ["Exp"], icon: "icons/Gloo.png", metaTier: "B" },
  { name: "Beatrix", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Beatrix.png", metaTier: "F" },
  { name: "Phoveus", roles: ["Fighter"], lanes: ["Exp"], icon: "icons/Phoveus.png", metaTier: "A" },
  { name: "Natan", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Natan.png", metaTier: "F" },
  { name: "Aulus", roles: ["Fighter"], lanes: ["Jungle", "Gold"], icon: "icons/Aulus.png", metaTier: "F" },
  { name: "Aamon", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Aamon.png", metaTier: "F" },
  { name: "Valentina", roles: ["Mage"], lanes: ["Exp", "Mid", "Gold"], icon: "icons/Valentina.png", metaTier: "A" },
  { name: "Edith", roles: ["Tank"], lanes: ["Exp", "Roam"], icon: "icons/Edith.png", metaTier: "F" },
  { name: "Floryn", roles: ["Support"], lanes: ["Roam"], icon: "icons/Floryn.png", metaTier: "Situational" },
  { name: "Yin", roles: ["Fighter", "Assassin"], lanes: ["Jungle"], icon: "icons/Yin.png", metaTier: "F" },
  { name: "Melissa", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Melissa.png", metaTier: "F" },
  { name: "Xavier", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Xavier.png", metaTier: "Situational" },
  { name: "Julian", roles: ["Assassin", "Fighter"], lanes: ["Jungle"], icon: "icons/Julian.png", metaTier: "Situational" },
  { name: "Fredrinn", roles: ["Fighter", "Tank"], lanes: ["Jungle"], icon: "icons/Fredrinn.png", metaTier: "S" },
  { name: "Joy", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Joy.png", metaTier: "A" },
  { name: "Novaria", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Novaria.png", metaTier: "Situational" },
  { name: "Arlott", roles: ["Fighter", "Assassin"], lanes: ["Exp"], icon: "icons/Arlott.png", metaTier: "A" },
  { name: "Ixia", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Ixia.png", metaTier: "F" },
  { name: "Nolan", roles: ["Assassin"], lanes: ["Jungle"], icon: "icons/Nolan.png", metaTier: "B" },
  { name: "Cici", roles: ["Fighter"], lanes: ["Exp", "Gold"], icon: "icons/Cici.png", metaTier: "B" },
  { name: "Chip", roles: ["Support", "Tank"], lanes: ["Roam"], icon: "icons/Chip.png", metaTier: "Situational" },
  { name: "Zhuxin", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Zhuxin.png", metaTier: "S" },
  { name: "Suyou", roles: ["Assassin", "Fighter"], lanes: ["Jungle"], icon: "icons/Suyou.png", metaTier: "B" },
  { name: "Lukas", roles: ["Fighter"], lanes: ["Exp", "Jungle"], icon: "icons/Lukas.png", metaTier: "B" },
  { name: "Kalea", roles: ["Support"], lanes: ["Roam"], icon: "icons/Kalea.png", metaTier: "A" },
  { name: "Zetian", roles: ["Mage"], lanes: ["Mid"], icon: "icons/Zetian.png", metaTier: "Situational" },
  { name: "Obsidia", roles: ["Marksman"], lanes: ["Gold"], icon: "icons/Obsidia.png", metaTier: "B" },
  { name: "Sora", roles: ["Fighter", "Assassin"], lanes: ["Exp", "Gold"], icon: "icons/Sora.png", metaTier: "S" }
];
